### ISSUE TITLE
Conduct a Digital Security vulnerability assessment (PeaceGeeks)

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/prj-nchrd#14]

**Comment by PeaceGeeks** [comment]
Moved to PeaceGeeks-IT repo

**Comment by PeaceGeeks** [comment]
Re-opening - this is project specific

**Comment by PeaceGeeks** [comment]
Assessment data collected - Kris to add additional details to the threat model report.
