### ISSUE TITLE
Set up Email Notification for Rocket.Chat

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-nchrd#22]

**Comment by improvethings** [comment]
Email notifications now work on user registration and on password resets.

**Comment by PeaceGeeksProjects** [comment]
@improvethings Not working for me this morning.  Cannot login waiting for registration confirmation email.

**Comment by PeaceGeeks** [comment]
Not working - can't reset password and can't get verification email

**Comment by improvethings** [comment]
Created a ticket: 
https://github.com/RocketChat/Rocket.Chat/issues/1993

**Comment by improvethings** [comment]
I have upgraded the server, and made the changes. I have rebooted the server, but it didn't come up as expected, so I will have to go into Backbone to the server room to debug.

**Comment by PeaceGeeksProjects** [comment]
@improvethings Still not working for me this morning. Cannot login waiting for registration confirmation email.

**Comment by improvethings** [comment]
I just tested it with a new account and new email address and it worked. 
Magdi: Can you try creating accounts with a couple different email addresses?

**Comment by PeaceGeeksProjects** [comment]
Worked for new accounts...  Can you please delete PeaceGeeksProjects,
MagdiRizkallah, & ChiefProjects Geek accounts

I'll then create a new account for PG projects


*Magdi Rizkallah*,
*Projects Director*
#210 - 128 West Hastings Street
Vancouver, BC, V6B 1G8
Projects@peacegeeks.org <magdi.rizallah@peacegeeks.org>

**Comment by improvethings** [comment]
All of your accounts have been removed.

**Comment by PeaceGeeks** [comment]
No longer required. This tool did not work properly for our needs.
