### ISSUE TITLE
Threat Modelling Review for NCHRD

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-nchrd#23]

**Comment by improvethings** [comment]
Can you please provide a description of what you'd like to see in various tickets as an expected outcome?

**Comment by improvethings** [comment]
This was assigned back to me without an answer? We need to make sure we read the updates before assigning to people. 

Also, can you please let me know where I can find their feedback? Is the document on files.peacegeeks.org?

**Comment by improvethings** [comment]
I have completed an initial draft, there is a lot more that should be done, but I think this is sufficient given the time constraints, and mobile martus minimizing the risk for most threats by deleting from the server as soon as submissions are sent. 
I have shared it with Renee: https://files.peacegeeks.org/index.php/s/T4EtvsdEVLRbS4q

I consider this closed unless there is more that is desired from this document.

**Comment by PeaceGeeks** [comment]
As discussed, please add context to this document

**Comment by improvethings** [comment]
I have uploaded a draft with context. Please close this if you are satisfied. 
https://files.peacegeeks.org/index.php/s/G8swiN0SPLVn9fL
