### ISSUE TITLE
Cannot do audio or video call from Jitsi

### ISSUE THREAD

**Issue by PeaceGeeksProjects** [PeaceGeeksSociety/prj-nchrd#28]

**Comment by PeaceGeeksProjects** [comment]
Worked fine this morning

**Comment by improvethings** [comment]
Can you please confirm this issue still exists, and if so, let me know and we can test it.

**Comment by PeaceGeeksProjects** [comment]
@improvethings can you connect to Jitsi and I will try this with you?

**Comment by improvethings** [comment]
I am online at kris@chat.peacegeeks.org

**Comment by PeaceGeeks** [comment]
We never got this working properly. Too late now .
