### ISSUE TITLE
Questions to NCHRD

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/prj-nchrd#32]
Ask NCHRD

One form with internal fields or two versions, one with and one without? 

How quickly do records get processed by HQ?

**Comment by PeaceGeeksProjects** [comment]
Why ask NCHRD???  We can decide on one form with internal fields otherwise we would need to link the 2 forms somehow adding complications...

**Comment by PeaceGeeks** [comment]
Yes to both forms. Magdi, these respond to two different use case scenarios: one for occasions where people can submit proper reports. One for people collecting rapid evidence, but can't submit a full report.
